apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mysql-persistent-noobaa
  labels:
    velero.io/storage-location: noobaa
  namespace: velero
spec:
  hooks: {}
  includedNamespaces:
  - mysql-persistent
  storageLocation: noobaa
  ttl: 720h0m0s
